alias ll="ls -la"
alias lrt="ls -lart"

alias ga="git add"
alias gaa="git add --all"
alias gbl="git branch -l"
alias gbr="git branch"
alias gc="git commit"
alias gci="git commit"
alias gcm="git commit --amend"
alias gco="git checkout"
alias gd="git diff"
alias gp="git pull"
alias gpp="git push"
alias gpf="git push --force"
alias gl="git log --pretty=oneline"
alias gll="git log"
alias glog="git log"
alias grs="git reset"
alias grb="git rebase"
alias gs="git status"
alias gst="git status"

alias mci="mvn clean install"
alias mi="mvn install"

alias mysql="winpty mysql"
